name = 'Bocos Dev Server'
port = 7788
players = 4098
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
language = 'de'
modules = ['js-module', 'js-bytecode-module', 'csharp-module']
resources = ['chat', 'server', 'client']