name = 'Bocos Dev Server'
port = 7788
players = 4098
debug = true
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
language = 'de'
modules = ['js-module', 'js-bytecode-module', 'csharp-module']
global-webcrypto = true
network-imports = true
resources = ['chat', 'server', 'client', 'reconnect']